# grafana/provisioning/datasources/datasource.yml

apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: ${PROMETHEUS_URL}
      isDefault: true
      editable: true

    - name: Loki
      type: loki
      access: proxy
      url: ${LOKI_URL}
      isDefault: false
      editable: true
