auth_enabled: false

server:
    http_listen_port: 3100
    grpc_listen_port: 9096

common:
    path_prefix: /loki
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
    replication_factor: 1
    ring:
        instance_addr: 127.0.0.1
        kvstore:
            store: inmemory

schema_config:
    configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
              prefix: index_
              period: 24h

storage_config:
    boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
        cache_ttl: 24h
        shared_store: filesystem
    filesystem:
        directory: /loki/chunks

compactor:
    working_directory: /loki/compactor
    shared_store: filesystem
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150

limits_config:
    retention_period: 744h
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m

chunk_store_config:
    max_look_back_period: 0s

table_manager:
    retention_deletes_enabled: true
    retention_period: 744h

ruler:
    storage:
        type: local
        local:
            directory: /loki/rules
    rule_path: /loki/rules-temp
    alertmanager_url: http://localhost:9093
    ring:
        kvstore:
            store: inmemory
    enable_api: true
