name: MLOps CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    # Step 1: Build Base Image with Dependencies
    build_and_cache_dependencies:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Dependency Image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest .
                  docker push ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest

    # Step 2: Training and Evaluating Model
    train_and_evaluate:
        runs-on: ubuntu-latest
        needs: build_and_cache_dependencies

        env:
            DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            # Pull the prebuilt Docker image with dependencies
            - name: Use Docker Image
              run: |
                  docker pull $DOCKER_IMAGE

            - name: Run Training and Evaluation
              run: |
                  docker run --rm -v ${{ github.workspace }}:/app $DOCKER_IMAGE bash -c "
                    cd /app &&
                    git config --global user.email 'actions@github.com' &&
                    git config --global user.name 'GitHub Actions' &&
                    dvc remote add -d supabase-s3 s3://MLOps --force &&
                    dvc remote modify supabase-s3 endpointurl '${{ secrets.SUPABASE_S3_ENDPOINT }}' &&
                    dvc remote modify supabase-s3 region '${{ secrets.SUPABASE_S3_REGION }}' &&
                    dvc remote modify supabase-s3 access_key_id '${{ secrets.SUPABASE_S3_ACCESS_KEY_ID }}' &&
                    dvc remote modify supabase-s3 secret_access_key '${{ secrets.SUPABASE_S3_SECRET_ACCESS_KEY }}' &&
                    dvc pull &&
                    python script/train.py &&
                    dvc push
                  "

    # Step 3: Build and Push Final Docker Image with Model
    build_and_push_docker:
        runs-on: ubuntu-latest
        needs: train_and_evaluate

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image with Model
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops_project:latest .

            - name: Push Docker Image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/mlops_project:latest
