name: MLOps CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    # Step 1: Build Base Image with Dependencies
    build_and_cache_dependencies:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Build and push the Docker image only if requirements have changed
            - name: Build and Push Dependency Image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest .
                  docker push ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest

    # Step 2: Training and Evaluating Model
    train_and_evaluate:
        runs-on: ubuntu-latest
        needs: build_and_cache_dependencies

        container: ${{ secrets.DOCKER_USERNAME }}/mlops_dependencies:latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            # Configure Git Identity and DVC as before
            - name: Configure Git Identity
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"

            - name: Remove dataset and model from Git tracking
              run: |
                  git rm -r --cached dataset || true
                  git rm -r --cached model || true
                  git commit -m "stop tracking dataset and model" --allow-empty

            - name: Configure DVC
              env:
                  SUPABASE_S3_ENDPOINT: ${{ secrets.SUPABASE_S3_ENDPOINT }}
                  SUPABASE_S3_REGION: ${{ secrets.SUPABASE_S3_REGION }}
                  SUPABASE_S3_ACCESS_KEY_ID: ${{ secrets.SUPABASE_S3_ACCESS_KEY_ID }}
                  SUPABASE_S3_SECRET_ACCESS_KEY: ${{ secrets.SUPABASE_S3_SECRET_ACCESS_KEY }}
              run: |
                  dvc remote add -d supabase-s3 s3://MLOps --force
                  dvc remote modify supabase-s3 endpointurl $SUPABASE_S3_ENDPOINT
                  dvc remote modify supabase-s3 region $SUPABASE_S3_REGION
                  dvc remote modify supabase-s3 access_key_id $SUPABASE_S3_ACCESS_KEY_ID
                  dvc remote modify supabase-s3 secret_access_key $SUPABASE_S3_SECRET_ACCESS_KEY

            # Continue with DVC tracking, data pull, and training steps
            - name: Add dataset and model to DVC tracking
              run: |
                  dvc add dataset
                  dvc add model

            - name: Pull Data from DVC Remote
              run: |
                  dvc pull

            - name: Run Training and Evaluation
              working-directory: script
              run: |
                  python train.py

            - name: Push to DVC Remote
              run: |
                  dvc push

    # Step 3: Build and Push Final Docker Image with Model
    build_and_push_docker:
        runs-on: ubuntu-latest
        needs: train_and_evaluate

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image with Model
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops_project:latest .

            - name: Push Docker Image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/mlops_project:latest
