name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Directory structure check
    - name: Check Directory Structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory structure:"
        ls -R

    - name: Run Training and Evaluation
      run: |
        python script/train.py
