name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Directory structure check for debugging paths
    - name: Check Directory Structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory structure:"
        ls -R

    # Set Working Directory to 'script' folder before running train.py
    - name: Set Working Directory to Script Folder
      working-directory: script
      run: |
        echo "Changed directory to script folder"
        pwd

    - name: Run Training and Evaluation
      working-directory: script
      run: |
        python train.py
        echo "Contents of script folder:"
        ls -R
        echo "Contents of mlruns folder:"
        ls -R mlruns

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: train_and_evaluate

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops_project:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mlops_project:latest
